// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Affix: typeof import('./src/components/Affix/index.vue')['default']
    CmsEdit: typeof import('./src/components/CmsEdit/index.vue')['default']
    CodeForm: typeof import('./src/components/SiteBuilderMenu/components/CodeForm.vue')['default']
    ContentCopy: typeof import('./src/components/ContentCopy/index.vue')['default']
    Default: typeof import('./src/components/Default/index.vue')['default']
    EdgeInput: typeof import('./src/components/TfrInput/EdgeInput.vue')['default']
    EditPageInfoWin: typeof import('./src/components/SiteBuilderMenu/EditPageInfoWin.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ImageForm: typeof import('./src/components/SiteBuilderMenu/components/ImageForm.vue')['default']
    InfoForm: typeof import('./src/components/SiteBuilderMenu/components/InfoForm.vue')['default']
    ItemChild: typeof import('./src/components/SecondSide/ItemChild.vue')['default']
    MaketingMenu: typeof import('./src/components/MaketingMenu/index.vue')['default']
    MenuItem: typeof import('./src/components/SecondSide/MenuItem.vue')['default']
    PageSelectWin: typeof import('./src/components/PageSelectWin/index.vue')['default']
    PlatformControl: typeof import('./src/components/PlatformControl/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecondSide: typeof import('./src/components/SecondSide/index.vue')['default']
    SeoForm: typeof import('./src/components/SiteBuilderMenu/components/SeoForm.vue')['default']
    SideMenu: typeof import('./src/components/SecondSide/SideMenu.vue')['default']
    SiteBuilderMenu: typeof import('./src/components/SiteBuilderMenu/index.vue')['default']
    StickyFlow: typeof import('./src/components/StickyFlow/index.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    TagForm: typeof import('./src/components/SiteBuilderMenu/components/TagForm.vue')['default']
    TfrButton: typeof import('./src/components/TfrButton/index.vue')['default']
    TfrCheckbox: typeof import('./src/components/TfrCheckbox/index.vue')['default']
    TfrDialog: typeof import('./src/components/TfrDialog/index.vue')['default']
    TfrInput: typeof import('./src/components/TfrInput/index.vue')['default']
    TfrLogo: typeof import('./src/components/TfrLogo/index.vue')['default']
    TfrSwitch: typeof import('./src/components/TfrSwitch/index.vue')['default']
  }
}

export {}
